# Config file for automatic testing at travis-ci.org

language: python

python:
    - "3.6"
    - "3.5"
    - "3.4"
    - "2.7"

sudo: false

env:
    - DJANGO=master
    - DJANGO=1.11
    - DJANGO=1.10
    - DJANGO=1.9
    - DJANGO=1.8

matrix:
    fast_finish: true
    include:
      - python: "3.3"
        env: DJANGO=1.8
    exclude:
      - python: "2.7"
        env: DJANGO=master
      - python: "3.4"
        env: DJANGO=master
      - python: "3.6"
        env: DJANGO=1.8
      - python: "3.6"
        env: DJANGO=1.9
      - python: "3.6"
        env: DJANGO=1.10
    allow_failures:
      - env: DJANGO=master

install: pip install tox-travis

# command to run tests using coverage, e.g. python setup.py test
script: tox

before_install:
  - pip install codecov

after_success:
  - tox -e coverage-report
  - codecov
